[project]
name = "threat-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "argparse>=1.4.0",
    "dotenv>=0.9.9",
    "google-genai>=1.41.0",
    "tinydb>=4.8.2",
]
